### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by AlbertoUrsino** [CremaLuca/SMSApp#3]
https://github.com/CremaLuca/SMSApp/blob/40dc610c5d96a40fbd4175d18e0050fdfe10c822/app/src/main/java/com/gruppo4/RingApplication/MainActivity.java#L54

**Comment by CremaLuca** [comment]
Cosa stai facendo

**Comment by AlbertoUrsino** [comment]
A quel tempo volevo sapere cos'erano gli issue
